/** Expert repair tips — generated by scripts/process-videos.py */
const EXPERT_TIPS = [
  {
    "id": "repair-life-hacks",
    "title": "3 решения в ремонте чтобы облегчить жизнь",
    "summary": "Три практичных решения, которые упрощают повседневную жизнь после ремонта.",
    "category": "Общее",
    "durationSec": 26,
    "cover": "assets/tips/repair-life-hacks/poster.jpg",
    "video": {
      "label": "3 решения в ремонте чтобы облегчить жизнь",
      "fileUrl": "assets/tips/repair-life-hacks/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/repair-life-hacks/poster.jpg"
    }
  },
  {
    "id": "outdated-solutions",
    "title": "3 устаревших решения - на что заменить",
    "summary": "Что уже не актуально в интерьере и чем заменить устаревшие приёмы.",
    "category": "Дизайн",
    "durationSec": 20,
    "cover": "assets/tips/outdated-solutions/poster.jpg",
    "video": {
      "label": "3 устаревших решения - на что заменить",
      "fileUrl": "assets/tips/outdated-solutions/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/outdated-solutions/poster.jpg"
    }
  },
  {
    "id": "design-tricks-5",
    "title": "5 дизайнерских фишек",
    "summary": "Пять приёмов, которые делают интерьер выразительнее без лишних затрат.",
    "category": "Дизайн",
    "durationSec": 33,
    "cover": "assets/tips/design-tricks-5/poster.jpg",
    "video": {
      "label": "5 дизайнерских фишек",
      "fileUrl": "assets/tips/design-tricks-5/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/design-tricks-5/poster.jpg"
    }
  },
  {
    "id": "modern-interior-5",
    "title": "5 идей в современном интерьере",
    "summary": "Современные идеи для интерьера: что работает сегодня и почему.",
    "category": "Дизайн",
    "durationSec": 120,
    "cover": "assets/tips/modern-interior-5/poster.jpg",
    "video": {
      "label": "5 идей в современном интерьере",
      "fileUrl": "assets/tips/modern-interior-5/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/modern-interior-5/poster.jpg"
    }
  },
  {
    "id": "built-in-coffee",
    "title": "Встроенная кофемашина",
    "summary": "Как встроить кофемашину в кухню: эргономика, коммуникации и обслуживание.",
    "category": "Кухня",
    "durationSec": 32,
    "cover": "assets/tips/built-in-coffee/poster.jpg",
    "video": {
      "label": "Встроенная кофемашина",
      "fileUrl": "assets/tips/built-in-coffee/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/built-in-coffee/poster.jpg"
    }
  },
  {
    "id": "wardrobe-small-bedroom",
    "title": "Гардеробная в маленькой спальне",
    "summary": "Как организовать гардеробную в компактной спальне без потери комфорта.",
    "category": "Планировка",
    "durationSec": 41,
    "cover": "assets/tips/wardrobe-small-bedroom/poster.jpg",
    "video": {
      "label": "Гардеробная в маленькой спальне",
      "fileUrl": "assets/tips/wardrobe-small-bedroom/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/wardrobe-small-bedroom/poster.jpg"
    }
  },
  {
    "id": "where-not-to-save",
    "title": "Где нельзя экономить",
    "summary": "На чём экономить опасно: узлы ремонта, где дешевизна оборачивается проблемами.",
    "category": "Бюджет",
    "durationSec": 48,
    "cover": "assets/tips/where-not-to-save/poster.jpg",
    "video": {
      "label": "Где нельзя экономить",
      "fileUrl": "assets/tips/where-not-to-save/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/where-not-to-save/poster.jpg"
    }
  },
  {
    "id": "hidden-doors-plinth",
    "title": "Двери скрытого монтажа и плинтус",
    "summary": "Скрытые двери и плинтус: как связать отделку и получить чистые линии.",
    "category": "Отделка",
    "durationSec": 21,
    "cover": "assets/tips/hidden-doors-plinth/poster.jpg",
    "video": {
      "label": "Двери скрытого монтажа и плинтус",
      "fileUrl": "assets/tips/hidden-doors-plinth/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/hidden-doors-plinth/poster.jpg"
    }
  },
  {
    "id": "installation-benefits",
    "title": "Еще одна польза инсталяции в санузле",
    "summary": "Дополнительные плюсы инсталляции в санузле помимо экономии места.",
    "category": "Санузел",
    "durationSec": 17,
    "cover": "assets/tips/installation-benefits/poster.jpg",
    "video": {
      "label": "Еще одна польза инсталяции в санузле",
      "fileUrl": "assets/tips/installation-benefits/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/installation-benefits/poster.jpg"
    }
  },
  {
    "id": "layout-importance",
    "title": "Зачем обращать внимание на планировку квартиры",
    "summary": "Почему планировка важнее отделки и как оценить квартиру до ремонта.",
    "category": "Планировка",
    "durationSec": 34,
    "cover": "assets/tips/layout-importance/poster.jpg",
    "video": {
      "label": "Зачем обращать внимание на планировку квартиры",
      "fileUrl": "assets/tips/layout-importance/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/layout-importance/poster.jpg"
    }
  },
  {
    "id": "electric-panel",
    "title": "Идеальный электрический щит",
    "summary": "Как должен быть устроен электрощит: безопасность, резерв и удобство.",
    "category": "Инженерия",
    "durationSec": 60,
    "cover": "assets/tips/electric-panel/poster.jpg",
    "video": {
      "label": "Идеальный электрический щит",
      "fileUrl": "assets/tips/electric-panel/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/electric-panel/poster.jpg"
    }
  },
  {
    "id": "kitchen-interior",
    "title": "Интерьер кухни",
    "summary": "Ключевые решения для функциональной и аккуратной кухни.",
    "category": "Кухня",
    "durationSec": 16,
    "cover": "assets/tips/kitchen-interior/poster.jpg",
    "video": {
      "label": "Интерьер кухни",
      "fileUrl": "assets/tips/kitchen-interior/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/kitchen-interior/poster.jpg"
    }
  },
  {
    "id": "kitchen-zone",
    "title": "Как правильно организовать кухонную зону",
    "summary": "Зонирование кухни: рабочий треугольник, хранение и освещение.",
    "category": "Кухня",
    "durationSec": 32,
    "cover": "assets/tips/kitchen-zone/poster.jpg",
    "video": {
      "label": "Как правильно организовать кухонную зону",
      "fileUrl": "assets/tips/kitchen-zone/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/kitchen-zone/poster.jpg"
    }
  },
  {
    "id": "beautiful-organized",
    "title": "Как сделать красиво и организованно",
    "summary": "Как совместить эстетику и порядок в интерьере без перегруза.",
    "category": "Планировка",
    "durationSec": 30,
    "cover": "assets/tips/beautiful-organized/poster.jpg",
    "video": {
      "label": "Как сделать красиво и организованно",
      "fileUrl": "assets/tips/beautiful-organized/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/beautiful-organized/poster.jpg"
    }
  },
  {
    "id": "wall-corners",
    "title": "Как сохранить углы стен",
    "summary": "Как защитить углы стен при ремонте и эксплуатации.",
    "category": "Отделка",
    "durationSec": 20,
    "cover": "assets/tips/wall-corners/poster.jpg",
    "video": {
      "label": "Как сохранить углы стен",
      "fileUrl": "assets/tips/wall-corners/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/wall-corners/poster.jpg"
    }
  },
  {
    "id": "plinth-timing",
    "title": "Когда устанавливать плинтус",
    "summary": "На каком этапе ремонта ставить плинтус и почему порядок важен.",
    "category": "Отделка",
    "durationSec": 33,
    "cover": "assets/tips/plinth-timing/poster.jpg",
    "video": {
      "label": "Когда устанавливать плинтус",
      "fileUrl": "assets/tips/plinth-timing/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/plinth-timing/poster.jpg"
    }
  },
  {
    "id": "hide-pipes-bathroom",
    "title": "Куда спрятать трубы в ванной",
    "summary": "Варианты маскировки труб в ванной с доступом для обслуживания.",
    "category": "Инженерия",
    "durationSec": 27,
    "cover": "assets/tips/hide-pipes-bathroom/poster.jpg",
    "video": {
      "label": "Куда спрятать трубы в ванной",
      "fileUrl": "assets/tips/hide-pipes-bathroom/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/hide-pipes-bathroom/poster.jpg"
    }
  },
  {
    "id": "water-heater-hack",
    "title": "Лайфхак с водонагревателем",
    "summary": "Практичный приём с водонагревателем для удобства и экономии места.",
    "category": "Инженерия",
    "durationSec": 20,
    "cover": "assets/tips/water-heater-hack/poster.jpg",
    "video": {
      "label": "Лайфхак с водонагревателем",
      "fileUrl": "assets/tips/water-heater-hack/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/water-heater-hack/poster.jpg"
    }
  },
  {
    "id": "heating-solutions",
    "title": "Не стандартные решения по отоплению",
    "summary": "Нестандартные решения по отоплению в современном интерьере.",
    "category": "Инженерия",
    "durationSec": 11,
    "cover": "assets/tips/heating-solutions/poster.jpg",
    "video": {
      "label": "Не стандартные решения по отоплению",
      "fileUrl": "assets/tips/heating-solutions/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/heating-solutions/poster.jpg"
    }
  },
  {
    "id": "bathroom-4sqm",
    "title": "Пример ванной комнаты 4 кв м",
    "summary": "Разбор планировки и отделки ванной площадью 4 м².",
    "category": "Санузел",
    "durationSec": 58,
    "cover": "assets/tips/bathroom-4sqm/poster.jpg",
    "video": {
      "label": "Пример ванной комнаты 4 кв м",
      "fileUrl": "assets/tips/bathroom-4sqm/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/bathroom-4sqm/poster.jpg"
    }
  },
  {
    "id": "bathroom-7sqm",
    "title": "Санузел 7 кв м",
    "summary": "Как распределить зоны в санузле 7 м²: душ, сантехника, хранение.",
    "category": "Санузел",
    "durationSec": 25,
    "cover": "assets/tips/bathroom-7sqm/poster.jpg",
    "video": {
      "label": "Санузел 7 кв м",
      "fileUrl": "assets/tips/bathroom-7sqm/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/bathroom-7sqm/poster.jpg"
    }
  },
  {
    "id": "secret-pantry",
    "title": "Секретная кладовая",
    "summary": "Скрытая кладовая в интерьере: где разместить и как спрятать.",
    "category": "Планировка",
    "durationSec": 11,
    "cover": "assets/tips/secret-pantry/poster.jpg",
    "video": {
      "label": "Секретная кладовая",
      "fileUrl": "assets/tips/secret-pantry/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/secret-pantry/poster.jpg"
    }
  },
  {
    "id": "minimalism-secrets",
    "title": "Секреты минимализма в интерьере",
    "summary": "Как сделать минималистичный интерьер тёплым и жилым.",
    "category": "Дизайн",
    "durationSec": 56,
    "cover": "assets/tips/minimalism-secrets/poster.jpg",
    "video": {
      "label": "Секреты минимализма в интерьере",
      "fileUrl": "assets/tips/minimalism-secrets/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/minimalism-secrets/poster.jpg"
    }
  },
  {
    "id": "low-price-danger",
    "title": "Чем опасна низная цена в ремонте",
    "summary": "Риски дешёвого ремонта: где экономия превращается в переделки.",
    "category": "Бюджет",
    "durationSec": 32,
    "cover": "assets/tips/low-price-danger/poster.jpg",
    "video": {
      "label": "Чем опасна низная цена в ремонте",
      "fileUrl": "assets/tips/low-price-danger/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/low-price-danger/poster.jpg"
    }
  },
  {
    "id": "shadow-plinth",
    "title": "Что важно знать о теневом плинтусе",
    "summary": "Теневой плинтус: монтаж, сочетание с полом и типичные ошибки.",
    "category": "Отделка",
    "durationSec": 20,
    "cover": "assets/tips/shadow-plinth/poster.jpg",
    "video": {
      "label": "Что важно знать о теневом плинтусе",
      "fileUrl": "assets/tips/shadow-plinth/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/shadow-plinth/poster.jpg"
    }
  },
  {
    "id": "bathroom-door-seam",
    "title": "Шов примыкания под дверью в санузел",
    "summary": "Как оформить шов примыкания пола к санузлу под дверью.",
    "category": "Санузел",
    "durationSec": 42,
    "cover": "assets/tips/bathroom-door-seam/poster.jpg",
    "video": {
      "label": "Шов примыкания под дверью в санузел",
      "fileUrl": "assets/tips/bathroom-door-seam/video.mp4",
      "embedUrl": null,
      "poster": "assets/tips/bathroom-door-seam/poster.jpg"
    }
  }
];

function getTipCategories() {
  const cats = new Set(EXPERT_TIPS.map((t) => t.category));
  return Array.from(cats).sort((a, b) => a.localeCompare(b, "ru"));
}

function getTipById(id) {
  return EXPERT_TIPS.find((t) => t.id === id);
}
