#!/usr/bin/env python3
"""Build step for the catalog: content/cases/*.json -> js/data.js, cases/<slug>/index.html,
js/tips-data.js -> tips/<slug>/index.html, sitemap.xml, cache-bust versions and
JSON-LD blocks in the root HTML pages.

Run after any change in content/, js/, css/ or assets/:
    python scripts/build-pages.py
"""

from __future__ import annotations

import datetime as dt
import hashlib
import html
import json
import re
import shutil
import subprocess
import sys
from functools import lru_cache
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from media_protect import VARIANT_WIDTHS

ROOT = Path(__file__).resolve().parents[1]
CONTENT_DIR = ROOT / "content"
CASES_DIR = CONTENT_DIR / "cases"
PAGES_DIR = ROOT / "cases"
TIPS_PAGES_DIR = ROOT / "tips"
TIPS_DATA_JS = ROOT / "js" / "tips-data.js"
DATA_JS = ROOT / "js" / "data.js"
CONFIG_JS = ROOT / "js" / "config.js"
SITEMAP = ROOT / "sitemap.xml"

GENERATED_NOTE = "AUTO-GENERATED by scripts/build-pages.py — do not edit by hand."

# Files whose ?v= references get refreshed with a content hash.
VERSIONED_HTML = ["index.html", "case.html", "tips.html", "404.html"]


def esc(value: object) -> str:
    return html.escape(str(value if value is not None else ""), quote=True)


def load_site() -> dict:
    return json.loads((CONTENT_DIR / "site.json").read_text(encoding="utf-8"))


def load_cases() -> list[dict]:
    cases = []
    for path in sorted(CASES_DIR.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        if data.get("id") != path.stem:
            raise SystemExit(f"Case id mismatch: {path.name} has id={data.get('id')!r}")
        cases.append(data)
    cases.sort(key=lambda c: (c.get("order", 10_000), c["id"]))
    return cases


def load_tips() -> list[dict]:
    """EXPERT_TIPS from js/tips-data.js (generated by scripts/process-videos.py)."""
    if not TIPS_DATA_JS.is_file():
        return []
    text = TIPS_DATA_JS.read_text(encoding="utf-8")
    match = re.search(r"const EXPERT_TIPS = (\[.*?\]);", text, re.DOTALL)
    if not match:
        raise SystemExit("js/tips-data.js: EXPERT_TIPS array not found")
    return json.loads(match.group(1))


def abs_url(site: dict, rel: str) -> str:
    return site["siteUrl"].rstrip("/") + "/" + rel.lstrip("/")


def case_url(site: dict, case_id: str) -> str:
    return abs_url(site, f"cases/{case_id}/")


def tip_url(site: dict, tip_id: str) -> str:
    return abs_url(site, f"tips/{tip_id}/")


# --------------------------------------------------------------------------
# Responsive image helpers (mirror scripts/media_protect.py naming scheme)
# --------------------------------------------------------------------------

def variant_path(src: str, *, width: int | None = None, webp: bool = False) -> str:
    p = Path(src)
    stem = p.stem if width is None else f"{p.stem}-{width}"
    suffix = ".webp" if webp else p.suffix
    return str(p.with_name(stem + suffix)).replace("\\", "/")


def existing(rel: str) -> bool:
    return (ROOT / rel).is_file()


@lru_cache(maxsize=None)
def image_width(rel: str) -> int | None:
    """Real pixel width of a master image (for the `w` srcset descriptor)."""
    path = ROOT / rel
    if not path.is_file():
        return None
    try:
        from PIL import Image

        with Image.open(path) as img:
            return img.size[0]
    except Exception:
        return None


def image_srcset(src: str, *, prefix: str = "", webp: bool = False) -> str | None:
    """srcset with every generated width variant plus the full-size master."""
    entries = []
    for w in VARIANT_WIDTHS:
        variant = variant_path(src, width=w, webp=webp)
        if existing(variant):
            entries.append(f"{prefix}{variant} {w}w")
    full = variant_path(src, webp=webp)
    full_width = image_width(src)
    if existing(full) and full_width:
        entries.append(f"{prefix}{full} {full_width}w")
    return ", ".join(entries) if entries else None


def picture_html(
    src: str,
    alt: str,
    *,
    prefix: str = "",
    css_class: str = "",
    width: int = 800,
    height: int = 600,
    sizes: str = "100vw",
    lazy: bool = True,
    high_priority: bool = False,
) -> str:
    """<picture> with webp + narrow variants when they exist on disk."""
    perf = 'decoding="async"'
    if high_priority:
        perf += ' fetchpriority="high"'
    elif lazy:
        perf += ' loading="lazy" fetchpriority="low"'
    cls = f' class="{esc(css_class)}"' if css_class else ""

    webp_set = image_srcset(src, prefix=prefix, webp=True)
    jpg_set = image_srcset(src, prefix=prefix, webp=False)

    sources = ""
    if webp_set:
        sources += f'<source type="image/webp" srcset="{esc(webp_set)}" sizes="{esc(sizes)}" />'
    img_srcset = f' srcset="{esc(jpg_set)}" sizes="{esc(sizes)}"' if jpg_set and ", " in jpg_set else ""
    img = (
        f'<img{cls} src="{esc(prefix + src)}"{img_srcset} alt="{esc(alt)}" '
        f'width="{width}" height="{height}" {perf} />'
    )
    if sources:
        return f"<picture>{sources}{img}</picture>"
    return img


# --------------------------------------------------------------------------
# js/data.js + js/config.js
# --------------------------------------------------------------------------

def build_data_js(cases: list[dict]) -> str:
    public = []
    for c in cases:
        entry = {k: v for k, v in c.items() if k != "order"}
        # Derived responsive-image fields for the catalog cards (js/catalog.js).
        entry["coverSrcset"] = image_srcset(c["cover"], webp=False)
        entry["coverWebpSrcset"] = image_srcset(c["cover"], webp=True)
        public.append(entry)
    payload = json.dumps(public, ensure_ascii=False, indent=2)
    return (
        f"// {GENERATED_NOTE}\n"
        "// Source of truth: content/cases/*.json. Edit those files, then run the build.\n"
        f"const CASES = {payload};\n\n"
        "/** Уникальные ЖК из базы */\n"
        "function getComplexes() {\n"
        "  const set = new Set(CASES.map((c) => c.complex));\n"
        "  return Array.from(set).sort();\n"
        "}\n"
    )


def build_config_js(site: dict) -> str:
    config = {
        "siteUrl": site["siteUrl"],
        "metrikaId": site.get("metrikaId"),
    }
    payload = json.dumps(config, ensure_ascii=False)
    return f"// {GENERATED_NOTE}\nwindow.ZK_CONFIG = {payload};\n"


# --------------------------------------------------------------------------
# Static case pages
# --------------------------------------------------------------------------

def json_ld_case(site: dict, c: dict) -> str:
    url = case_url(site, c["id"])
    images = [abs_url(site, g["src"]) for g in c.get("gallery", [])][:10]
    if c.get("cover") and abs_url(site, c["cover"]) not in images:
        images.insert(0, abs_url(site, c["cover"]))

    graph = [
        {
            "@type": "BreadcrumbList",
            "itemListElement": [
                {
                    "@type": "ListItem",
                    "position": 1,
                    "name": "Каталог работ",
                    "item": abs_url(site, ""),
                },
                {
                    "@type": "ListItem",
                    "position": 2,
                    "name": c["title"],
                    "item": url,
                },
            ],
        },
        {
            "@type": "CreativeWork",
            "@id": url + "#case",
            "name": f'{c["title"]} — {c.get("areaLabel", "")}'.strip(" —"),
            "url": url,
            "description": c.get("summary", ""),
            "image": images,
            "locationCreated": {
                "@type": "Place",
                "address": {
                    "@type": "PostalAddress",
                    "addressLocality": site["city"],
                    "addressCountry": site["country"],
                    "streetAddress": c.get("address", ""),
                },
            },
            "creator": {"@id": abs_url(site, "") + "#business"},
            "keywords": ", ".join(c.get("tags", [])),
        },
    ]
    if c.get("hasVideo") and c.get("video", {}).get("fileUrl"):
        graph.append(
            {
                "@type": "VideoObject",
                "name": c["video"].get("label") or f'Видеообзор: {c["title"]}',
                "description": c.get("summary", ""),
                "contentUrl": abs_url(site, c["video"]["fileUrl"]),
                "thumbnailUrl": abs_url(site, c["video"].get("poster") or c["cover"]),
                # Дата привязана к mtime JSON кейса, чтобы пересборка была детерминированной.
                "uploadDate": file_date(CASES_DIR / f'{c["id"]}.json'),
            }
        )
    data = {"@context": "https://schema.org", "@graph": graph}
    return json.dumps(data, ensure_ascii=False, indent=2)


def today_iso() -> str:
    return dt.date.today().isoformat()


@lru_cache(maxsize=None)
def git_commit_date(rel: str) -> str | None:
    """Date (YYYY-MM-DD) of the last commit touching the file, if any."""
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", rel],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=15,
            check=False,
        )
        value = out.stdout.strip()
        return value or None
    except (OSError, subprocess.SubprocessError):
        return None


def file_date(path: Path) -> str:
    """Real content date: last git commit, else mtime (uncommitted files)."""
    if path.is_file():
        rel = path.relative_to(ROOT).as_posix()
        committed = git_commit_date(rel)
        if committed:
            return committed
        return dt.date.fromtimestamp(path.stat().st_mtime).isoformat()
    return today_iso()


def gallery_figure(g: dict, fallback_caption: str, *, prefix: str, sizes: str) -> str:
    caption = g.get("caption") or fallback_caption
    picture = picture_html(
        g["src"],
        g.get("alt") or fallback_caption,
        prefix=prefix,
        sizes=sizes,
        width=800,
        height=600,
    )
    return f"<figure>{picture}<figcaption>{esc(caption)}</figcaption></figure>"


def video_block(c: dict, prefix: str) -> str:
    video = c.get("video") or {}
    label = video.get("label") or "Видео"
    if video.get("embedUrl"):
        inner = (
            f'<div class="video-block"><iframe title="{esc(label)}" src="{esc(video["embedUrl"])}" '
            'allowfullscreen loading="lazy"></iframe></div>'
        )
    elif video.get("fileUrl"):
        poster = f'{prefix}{video.get("poster") or c["cover"]}'
        mime = "video/quicktime" if video["fileUrl"].lower().endswith(".mov") else "video/mp4"
        inner = (
            '<div class="video-block"><video controls controlsList="nodownload noplaybackrate" '
            f'disablePictureInPicture playsinline preload="none" poster="{esc(poster)}">'
            f'<source src="{esc(prefix + video["fileUrl"])}" type="{mime}" />'
            "Ваш браузер не поддерживает видео.</video></div>"
        )
    elif video.get("externalUrl"):
        inner = (
            f'<p><a class="btn btn--primary" href="{esc(video["externalUrl"])}" target="_blank" '
            'rel="noopener noreferrer">Смотреть видео</a></p>'
        )
    else:
        return ""
    return f'<section class="section"><h2>{esc(label)}</h2>{inner}</section>'


def footer_html(site: dict, prefix: str) -> str:
    return f"""
    <footer class="site-footer">
      <div class="container">
        <div class="site-footer__top">
          <div class="site-footer__brand">
            <strong>За Комфортом</strong>
            <span>Студия дизайна и ремонта · Уфа</span>
          </div>
          <div class="site-footer__actions">
            <a class="btn btn--primary" href="{esc(site["mainSite"])}" target="_blank" rel="noopener noreferrer">Рассчитать ремонт</a>
            <a class="site-footer__phone" href="tel:{esc(site["phoneHref"])}">{esc(site["phone"])}</a>
          </div>
        </div>
        <div class="site-footer__messengers" aria-label="Мессенджеры">
          <a class="social-link social-link--whatsapp" href="{esc(site["whatsapp"])}" target="_blank" rel="noopener noreferrer">
            <svg class="social-link__icon" aria-hidden="true"><use href="{prefix}assets/brand/social-icons.svg#icon-whatsapp"></use></svg>
            <span>WhatsApp</span>
          </a>
          <a class="social-link social-link--telegram" href="{esc(site["telegram"])}" target="_blank" rel="noopener noreferrer">
            <svg class="social-link__icon" aria-hidden="true"><use href="{prefix}assets/brand/social-icons.svg#icon-telegram"></use></svg>
            <span>Telegram</span>
          </a>
          <a class="social-link social-link--max" href="{esc(site["max"])}" target="_blank" rel="noopener noreferrer">
            <img class="social-link__icon social-link__icon--brand" src="{prefix}assets/brand/max-icon.png" alt="" width="18" height="18" decoding="async" />
            <span>Max</span>
          </a>
          <a class="social-link social-link--vk" href="{esc(site["vk"])}" target="_blank" rel="noopener noreferrer">
            <svg class="social-link__icon" aria-hidden="true"><use href="{prefix}assets/brand/social-icons.svg#icon-vk"></use></svg>
            <span>VK</span>
          </a>
        </div>
      </div>
    </footer>"""


def build_case_page(site: dict, c: dict, versions: dict[str, str]) -> str:
    prefix = "../../"
    url = case_url(site, c["id"])
    title = f'{c["title"]} · {c.get("areaLabel", "")} · За Комфортом'
    description = c.get("summary", "")
    og_image = abs_url(site, c["cover"])
    photo_caption = c["title"]
    gallery_sizes = "(min-width: 800px) 33vw, (min-width: 560px) 50vw, 100vw"

    def v(rel: str) -> str:
        return f"{prefix}{rel}?v={versions[rel]}"

    work_list = (
        '<ul class="list-check">'
        + "".join(f"<li>{esc(x)}</li>" for x in c.get("workList", []))
        + "</ul>"
        if c.get("workList")
        else "<p>Состав работ уточняется под конкретный объект.</p>"
    )

    plan = c.get("plan")
    if plan:
        plan_html = (
            '<div class="gallery"><figure>'
            + picture_html(
                plan["src"],
                plan.get("alt") or "План объекта",
                prefix=prefix,
                sizes=gallery_sizes,
                width=1200,
                height=800,
            )
            + f'<figcaption>{esc(plan.get("caption", ""))}</figcaption></figure></div>'
        )
    else:
        plan_html = "<p>План объекта будет добавлен.</p>"

    gallery_html = "".join(
        gallery_figure(g, photo_caption, prefix=prefix, sizes=gallery_sizes)
        for g in c.get("gallery", [])
        if g["src"] != c["cover"]
    )
    before_items = c.get("beforeGallery") or []
    before_html = (
        f'<div class="gallery">{"".join(gallery_figure(g, photo_caption, prefix=prefix, sizes=gallery_sizes) for g in before_items)}</div>'
        if before_items
        else "<p>Фото до ремонта не добавлены.</p>"
    )
    compare_items = c.get("compareGallery") or []
    compare_html = (
        '<section class="section"><h2>Проект / реализация</h2><div class="gallery">'
        + "".join(gallery_figure(g, photo_caption, prefix=prefix, sizes=gallery_sizes) for g in compare_items)
        + "</div></section>"
        if compare_items
        else ""
    )

    hero_picture = picture_html(
        c["cover"],
        c["title"],
        prefix=prefix,
        css_class="case-hero__img",
        width=1600,
        height=900,
        sizes="100vw",
        lazy=False,
        high_priority=True,
    )

    hero_webp_set = image_srcset(c["cover"], prefix=prefix, webp=True)
    if hero_webp_set:
        hero_preload = (
            f'<link rel="preload" as="image" imagesrcset="{esc(hero_webp_set)}" '
            'imagesizes="100vw" fetchpriority="high" />'
        )
    else:
        hero_preload = (
            f'<link rel="preload" as="image" href="{prefix}{esc(c["cover"])}" '
            'fetchpriority="high" />'
        )

    address_html = (
        f'<p><strong>Адрес:</strong> {esc(c["address"])}</p>' if c.get("address") else ""
    )
    quiz_url = (c.get("cta") or {}).get("quiz") or site["quiz"]
    cta_label = (c.get("cta") or {}).get("buttonLabel") or "Обсудить похожий дизайн"

    return f"""<!DOCTYPE html>
<!-- {GENERATED_NOTE} Source: content/cases/{c["id"]}.json -->
<html lang="ru">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <meta name="robots" content="index, follow" />
    <meta name="theme-color" content="#1f5f4e" />
    <title>{esc(title)}</title>
    <meta name="description" content="{esc(description)}" />
    <link rel="canonical" href="{esc(url)}" />
    <link rel="icon" type="image/png" href="{prefix}assets/brand/logo.png" />
    <link rel="apple-touch-icon" href="{prefix}assets/brand/logo.png" />

    <link rel="preconnect" href="https://zakomfortom.com" crossorigin />
    {hero_preload}

    <meta property="og:type" content="article" />
    <meta property="og:locale" content="ru_RU" />
    <meta property="og:site_name" content="За Комфортом" />
    <meta property="og:url" content="{esc(url)}" />
    <meta property="og:title" content="{esc(c["title"])} · {esc(c.get("areaLabel", ""))}" />
    <meta property="og:description" content="{esc(description)}" />
    <meta property="og:image" content="{esc(og_image)}" />
    <meta property="og:image:width" content="1440" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="{esc(c["title"])} · {esc(c.get("areaLabel", ""))}" />
    <meta name="twitter:description" content="{esc(description)}" />
    <meta name="twitter:image" content="{esc(og_image)}" />

    <link rel="stylesheet" href="{v("css/styles.css")}" />
    <script type="application/ld+json">
{json_ld_case(site, c)}
    </script>
  </head>
  <body>
    <header class="site-header">
      <div class="site-header__inner">
        <a class="logo" href="{prefix}index.html" aria-label="За Комфортом">
          <img class="logo__img" src="{prefix}assets/brand/logo.png" alt="За Комфортом" />
        </a>
        <nav class="nav-links" aria-label="Навигация">
          <a href="{prefix}index.html">Каталог</a>
          <a href="{prefix}tips.html">Советы эксперта</a>
          <a href="{esc(site["mainSite"])}" target="_blank" rel="noopener noreferrer">Рассчитать ремонт</a>
        </nav>
      </div>
    </header>
    <main id="case-root">
      <div class="case-hero">
        {hero_picture}
        <div class="case-hero__content container">
          <h1>{esc(c["title"])}</h1>
          <p class="case-hero__meta">{esc(c.get("areaLabel", ""))} · {esc(c.get("format", ""))} · {esc(c.get("style", ""))}</p>
          <div class="case-actions">
            <a class="btn btn--primary" href="#gallery">Смотреть фото</a>
            <a class="btn btn--ghost" href="{esc(site["mainSite"])}" target="_blank" rel="noopener noreferrer">Рассчитать похожий ремонт</a>
            <a class="btn btn--ghost" href="{prefix}tips.html">Советы эксперта</a>
          </div>
        </div>
      </div>

      <div class="container">
        <section class="section">
          <h2>Паспорт объекта</h2>
          <p><strong>Площадь:</strong> {esc(c.get("areaLabel", ""))} · <strong>Тип:</strong> {esc(c.get("roomsLabel") or "квартира")} · <strong>Формат:</strong> {esc(c.get("format", ""))} · <strong>Сегмент:</strong> {esc(c.get("segment", ""))}</p>
          {address_html}
        </section>

        <section class="section">
          <h2>Запрос заказчика</h2>
          <p>{esc(c.get("task", ""))}</p>
        </section>

        <section class="section">
          <h2>План и описание объекта</h2>
          <p>{esc(c.get("objectDescription", ""))}</p>
          {plan_html}
        </section>

        <section class="section">
          <h2>Краткий список работ</h2>
          {work_list}
        </section>

        <section class="section">
          <h2>Проект и реализация</h2>
          <ul class="list-check">
            {"".join(f"<li>{esc(x)}</li>" for x in c.get("highlights", []))}
          </ul>
        </section>

        <section class="section" id="gallery">
          <h2>Галерея</h2>
          <div class="gallery">
            {gallery_html}
          </div>
        </section>

        <section class="section">
          <h2>Фото до ремонта</h2>
          {before_html}
        </section>

        {compare_html}

        {video_block(c, prefix)}

        <section class="section section--fit">
          <h2>Если узнаёте себя</h2>
          <ul class="list-check list-check--fit">
            {"".join(f"<li>{esc(x)}</li>" for x in c.get("clientFit", []))}
          </ul>
          <p class="section-cta"><a class="btn btn--primary" href="{esc(quiz_url)}" target="_blank" rel="noopener noreferrer">{esc(cta_label)}</a></p>
        </section>
      </div>
    </main>
{footer_html(site, prefix)}

    <script src="{v("js/config.js")}" defer></script>
    <script src="{v("js/metrika.js")}" defer></script>
    <script src="{v("js/media-guard.js")}" defer></script>
    <script src="{v("js/case-page.js")}" defer></script>
  </body>
</html>
"""


# --------------------------------------------------------------------------
# Static tip pages (tips/<slug>/index.html)
# --------------------------------------------------------------------------

def format_duration(seconds: object) -> str:
    """Mirror of formatDuration in js/media-utils.js (m:ss)."""
    if not isinstance(seconds, (int, float)) or seconds <= 0:
        return ""
    total = int(seconds)
    return f"{total // 60}:{total % 60:02d}"


def tip_asset_date(tip: dict) -> str:
    video = tip.get("video") or {}
    file_url = video.get("fileUrl")
    if isinstance(file_url, str) and file_url:
        return file_date(ROOT / file_url)
    return file_date(TIPS_DATA_JS)


def json_ld_tip(site: dict, tip: dict) -> str:
    url = tip_url(site, tip["id"])
    video = tip.get("video") or {}
    graph: list[dict] = [
        {
            "@type": "BreadcrumbList",
            "itemListElement": [
                {
                    "@type": "ListItem",
                    "position": 1,
                    "name": "Каталог работ",
                    "item": abs_url(site, ""),
                },
                {
                    "@type": "ListItem",
                    "position": 2,
                    "name": "Советы эксперта",
                    "item": abs_url(site, "tips.html"),
                },
                {
                    "@type": "ListItem",
                    "position": 3,
                    "name": tip["title"],
                    "item": url,
                },
            ],
        }
    ]
    if video.get("fileUrl"):
        video_ld = {
            "@type": "VideoObject",
            "name": tip["title"],
            "description": tip.get("summary", ""),
            "contentUrl": abs_url(site, video["fileUrl"]),
            "thumbnailUrl": abs_url(site, video.get("poster") or tip["cover"]),
            "uploadDate": tip_asset_date(tip),
        }
        duration = tip.get("durationSec")
        if isinstance(duration, (int, float)) and duration > 0:
            video_ld["duration"] = f"PT{int(duration)}S"
        graph.append(video_ld)
    data = {"@context": "https://schema.org", "@graph": graph}
    return json.dumps(data, ensure_ascii=False, indent=2)


def tip_card_html(tip: dict, *, prefix: str) -> str:
    duration = format_duration(tip.get("durationSec"))
    duration_html = (
        f'<span class="tip-card__duration" aria-label="Длительность {esc(duration)}">{esc(duration)}</span>'
        if duration
        else ""
    )
    return (
        f'<a class="tip-card tip-card--compact" href="../{esc(tip["id"])}/" '
        f'aria-label="Смотреть: {esc(tip["title"])}">'
        '<div class="tip-card__media">'
        f'<img src="{esc(prefix + tip["cover"])}" alt="" width="404" height="720" loading="lazy" decoding="async" />'
        '<span class="tip-card__play" aria-hidden="true"></span>'
        f"{duration_html}"
        "</div>"
        '<div class="tip-card__body">'
        f'<span class="tip-card__category">{esc(tip["category"])}</span>'
        f'<h3 class="tip-card__title">{esc(tip["title"])}</h3>'
        "</div>"
        "</a>"
    )


def tip_video_html(tip: dict, *, prefix: str) -> str:
    video = tip.get("video") or {}
    if video.get("embedUrl"):
        return (
            f'<div class="video-block"><iframe title="{esc(tip["title"])}" '
            f'src="{esc(video["embedUrl"])}" allowfullscreen loading="lazy"></iframe></div>'
        )
    if video.get("fileUrl"):
        poster = prefix + (video.get("poster") or tip["cover"])
        mime = "video/quicktime" if video["fileUrl"].lower().endswith(".mov") else "video/mp4"
        return (
            '<div class="video-block"><video controls controlsList="nodownload noplaybackrate" '
            f'disablePictureInPicture playsinline preload="none" poster="{esc(poster)}">'
            f'<source src="{esc(prefix + video["fileUrl"])}" type="{mime}" />'
            "Ваш браузер не поддерживает видео.</video></div>"
        )
    return ""


def build_tip_page(site: dict, tip: dict, tips: list[dict], versions: dict[str, str]) -> str:
    prefix = "../../"
    url = tip_url(site, tip["id"])
    title = f'{tip["title"]} · Советы эксперта · За Комфортом'
    description = tip.get("summary", "")
    og_image = abs_url(site, tip["cover"])
    category_href = f'{prefix}tips.html?category={esc(tip["category"])}'

    def v(rel: str) -> str:
        return f"{prefix}{rel}?v={versions[rel]}"

    related = [t for t in tips if t["category"] == tip["category"] and t["id"] != tip["id"]][:3]
    related_html = (
        '<section class="section"><h2>Похожие советы</h2>'
        '<div class="tip-grid tip-grid--related">'
        + "".join(tip_card_html(t, prefix=prefix) for t in related)
        + "</div></section>"
        if related
        else ""
    )

    return f"""<!DOCTYPE html>
<!-- {GENERATED_NOTE} Source: js/tips-data.js (id: {tip["id"]}) -->
<html lang="ru">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <meta name="robots" content="index, follow" />
    <meta name="theme-color" content="#1f5f4e" />
    <title>{esc(title)}</title>
    <meta name="description" content="{esc(description)}" />
    <link rel="canonical" href="{esc(url)}" />
    <link rel="icon" type="image/png" href="{prefix}assets/brand/logo.png" />
    <link rel="apple-touch-icon" href="{prefix}assets/brand/logo.png" />

    <link rel="preconnect" href="https://zakomfortom.com" crossorigin />

    <meta property="og:type" content="video.other" />
    <meta property="og:locale" content="ru_RU" />
    <meta property="og:site_name" content="За Комфортом" />
    <meta property="og:url" content="{esc(url)}" />
    <meta property="og:title" content="{esc(tip["title"])}" />
    <meta property="og:description" content="{esc(description)}" />
    <meta property="og:image" content="{esc(og_image)}" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="{esc(tip["title"])}" />
    <meta name="twitter:description" content="{esc(description)}" />
    <meta name="twitter:image" content="{esc(og_image)}" />

    <link rel="stylesheet" href="{v("css/styles.css")}" />
    <script type="application/ld+json">
{json_ld_tip(site, tip)}
    </script>
  </head>
  <body>
    <header class="site-header">
      <div class="site-header__inner">
        <a class="logo" href="{prefix}index.html" aria-label="За Комфортом">
          <img class="logo__img" src="{prefix}assets/brand/logo.png" alt="За Комфортом" />
        </a>
        <nav class="nav-links" aria-label="Навигация">
          <a href="{prefix}index.html">Каталог</a>
          <a href="{prefix}tips.html" aria-current="page">Советы эксперта</a>
          <a href="{esc(site["mainSite"])}" target="_blank" rel="noopener noreferrer">Рассчитать ремонт</a>
        </nav>
      </div>
    </header>
    <main id="tips-root">
      <div class="container tip-detail">
        <nav class="tip-breadcrumbs" aria-label="Навигация">
          <a href="{prefix}tips.html">Все советы</a>
          <span aria-hidden="true">/</span>
          <a href="{category_href}">{esc(tip["category"])}</a>
        </nav>
        <h1>{esc(tip["title"])}</h1>
        {tip_video_html(tip, prefix=prefix)}
        <p class="lead">{esc(description)}</p>
        <p class="tip-detail__actions">
          <a class="btn btn--primary" href="{esc(site["mainSite"])}" target="_blank" rel="noopener noreferrer">Обсудить ремонт</a>
          <a class="btn btn--ghost" href="{prefix}tips.html">Все советы</a>
        </p>
      </div>
      <div class="container">
        {related_html}
      </div>
    </main>
{footer_html(site, prefix)}

    <script src="{v("js/config.js")}" defer></script>
    <script src="{v("js/metrika.js")}" defer></script>
    <script src="{v("js/media-guard.js")}" defer></script>
  </body>
</html>
"""


# --------------------------------------------------------------------------
# sitemap.xml
# --------------------------------------------------------------------------

def build_sitemap(site: dict, cases: list[dict], tips: list[dict]) -> str:
    def entry(loc: str, lastmod: str, priority: str) -> str:
        return (
            "  <url>\n"
            f"    <loc>{esc(loc)}</loc>\n"
            f"    <lastmod>{lastmod}</lastmod>\n"
            f"    <priority>{priority}</priority>\n"
            "  </url>"
        )

    rows = [
        entry(abs_url(site, ""), file_date(ROOT / "index.html"), "1.0"),
        entry(abs_url(site, "tips.html"), file_date(ROOT / "tips.html"), "0.7"),
    ]
    for c in cases:
        rows.append(
            entry(
                case_url(site, c["id"]),
                file_date(CASES_DIR / f'{c["id"]}.json'),
                "0.8",
            )
        )
    for tip in tips:
        rows.append(entry(tip_url(site, tip["id"]), tip_asset_date(tip), "0.6"))
    body = "\n".join(rows)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{body}\n"
        "</urlset>\n"
    )


# --------------------------------------------------------------------------
# Cache-bust versions + JSON-LD injection in the hand-written root pages
# --------------------------------------------------------------------------

def asset_versions() -> dict[str, str]:
    versions: dict[str, str] = {}
    for rel_dir, pattern in (("css", "*.css"), ("js", "*.js")):
        for path in sorted((ROOT / rel_dir).glob(pattern)):
            digest = hashlib.md5(path.read_bytes()).hexdigest()[:10]
            versions[f"{rel_dir}/{path.name}"] = digest
    return versions


# Matches css/js references with or without an existing ?v=; the version is
# (re)computed from file content, so hand-editing ?v= is never needed.
VERSION_REF_RE = re.compile(
    r'(href|src)="((?:\.\./)*/?(?:css|js)/[\w./-]+)(?:\?v=[^"]*)?"'
)


def apply_versions(text: str, versions: dict[str, str]) -> str:
    def repl(m: re.Match) -> str:
        attr, path = m.group(1), m.group(2)
        rel = re.sub(r"^(\.\./)*/?", "", path)
        version = versions.get(rel)
        if not version:
            return m.group(0)
        return f'{attr}="{path}?v={version}"'

    return VERSION_REF_RE.sub(repl, text)


def json_ld_home(site: dict, cases: list[dict]) -> str:
    business = {
        "@type": "HomeAndConstructionBusiness",
        "@id": abs_url(site, "") + "#business",
        "name": site["companyName"],
        "url": site["mainSite"],
        "logo": abs_url(site, site["logo"]),
        "image": abs_url(site, site["ogImage"]),
        "telephone": site["phone"],
        "address": {
            "@type": "PostalAddress",
            "addressLocality": site["city"],
            "addressRegion": site["region"],
            "addressCountry": site["country"],
        },
        "areaServed": site["city"],
        "sameAs": [site["vk"], site["telegramChannel"], site["twoGis"]],
    }
    item_list = {
        "@type": "ItemList",
        "@id": abs_url(site, "") + "#cases",
        "name": "Реализованные ремонты",
        "numberOfItems": len(cases),
        "itemListElement": [
            {
                "@type": "ListItem",
                "position": i + 1,
                "name": c["title"],
                "url": case_url(site, c["id"]),
            }
            for i, c in enumerate(cases)
        ],
    }
    data = {"@context": "https://schema.org", "@graph": [business, item_list]}
    return json.dumps(data, ensure_ascii=False, indent=2)


JSONLD_BLOCK_RE = re.compile(
    r"(<!-- build:jsonld -->).*?(<!-- /build:jsonld -->)", re.DOTALL
)


def inject_home_jsonld(text: str, site: dict, cases: list[dict]) -> str:
    block = (
        "<!-- build:jsonld -->\n"
        '    <script type="application/ld+json">\n'
        f"{json_ld_home(site, cases)}\n"
        "    </script>\n"
        "    <!-- /build:jsonld -->"
    )
    if JSONLD_BLOCK_RE.search(text):
        return JSONLD_BLOCK_RE.sub(lambda _: block, text)
    return text


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------

def main() -> int:
    site = load_site()
    cases = load_cases()
    tips = load_tips()

    # 1. Generated JS (data + config) — must exist before hashing versions.
    DATA_JS.write_text(build_data_js(cases), encoding="utf-8", newline="\n")
    print(f"generated: js/data.js ({len(cases)} cases)")
    CONFIG_JS.write_text(build_config_js(site), encoding="utf-8", newline="\n")
    print("generated: js/config.js")

    versions = asset_versions()

    # 2. Static case pages.
    known_ids = {c["id"] for c in cases}
    PAGES_DIR.mkdir(exist_ok=True)
    for stale in PAGES_DIR.iterdir():
        if stale.is_dir() and stale.name not in known_ids:
            shutil.rmtree(stale)
            print(f"removed stale page: cases/{stale.name}/")
    for c in cases:
        page_dir = PAGES_DIR / c["id"]
        page_dir.mkdir(parents=True, exist_ok=True)
        (page_dir / "index.html").write_text(
            build_case_page(site, c, versions), encoding="utf-8", newline="\n"
        )
        print(f'generated: cases/{c["id"]}/index.html')

    # 3. Static tip pages.
    known_tip_ids = {t["id"] for t in tips}
    TIPS_PAGES_DIR.mkdir(exist_ok=True)
    for stale in TIPS_PAGES_DIR.iterdir():
        if stale.is_dir() and stale.name not in known_tip_ids:
            shutil.rmtree(stale)
            print(f"removed stale page: tips/{stale.name}/")
    for tip in tips:
        page_dir = TIPS_PAGES_DIR / tip["id"]
        page_dir.mkdir(parents=True, exist_ok=True)
        (page_dir / "index.html").write_text(
            build_tip_page(site, tip, tips, versions), encoding="utf-8", newline="\n"
        )
    print(f"generated: tips/<slug>/index.html ({len(tips)} tips)")

    # 4. sitemap.xml
    SITEMAP.write_text(build_sitemap(site, cases, tips), encoding="utf-8", newline="\n")
    print("generated: sitemap.xml")

    # 5. Refresh ?v= versions and homepage JSON-LD in hand-written pages.
    for name in VERSIONED_HTML:
        path = ROOT / name
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")
        updated = apply_versions(text, versions)
        if name == "index.html":
            updated = inject_home_jsonld(updated, site, cases)
        if updated != text:
            path.write_text(updated, encoding="utf-8", newline="\n")
            print(f"updated: {name}")

    print("BUILD_OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
